name: nutricare
description: "NutriCare - Smart Nutrition Tracker"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.1
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.19.0
  salomon_bottom_bar: ^3.3.2
  csv: ^6.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tabel.csv
